/**
 * Generated by scripts/generate-placeholders.mjs. Listed explicitly rather
 * than read from disk so a missing file is a build-time type error instead of
 * a broken image in production.
 */
export const placeholderSlugs = [
  "candle-sylvan-mist",
  "candle-herbal-solace",
  "candle-sunlit-grove",
  "honey-kashmir-acacia",
  "honey-himalayan-forest",
  "honey-raw-sidr",
  "tisane-caddy",
  "mineral-soak",
  "chocolate-slab",
  "truffle-assortment",
  "glazed-nuts",
  "seed-paper-notebook",
  "moss-bowl-walnut",
  "moss-bowl-stone",
  "herbarium-frame",
  "brass-candle-care",
  "pearl-tasting-spoon",
  "scallop-catchall",
  "duo-scribes-sanctuary",
  "duo-botanical-nectar",
  "duo-tea-honey-cellar",
  "suite-botanical-harvest",
  "suite-biophilic-sanctuary",
  "suite-grand-heirloom",
] as const;

export type PlaceholderSlug = (typeof placeholderSlugs)[number];

const known = new Set<string>(placeholderSlugs);

export function placeholderFor(slug: string): string {
  return `/placeholders/${known.has(slug) ? slug : "default"}.svg`;
}
